# Application identity
APP_NAME=File Mover Portal
SECRET_KEY=replace-with-at-least-32-random-characters
FLASK_DEBUG=false

# Gunicorn listens on the Python application server's internal interface.
# Do not use 127.0.0.1 when IBM HTTP Server is on another host.
APP_HOST=10.20.30.40
APP_PORT=8000
GUNICORN_WORKERS=3
GUNICORN_THREADS=4
GUNICORN_TIMEOUT=120

# Exact IBM HTTP Server source IP(s), comma-separated. Never expose Gunicorn publicly.
TRUSTED_PROXY_IPS=10.20.30.25
TRUSTED_PROXY_COUNT=1

SOURCE_DIR=data/incoming
DESTINATION_DIR=data/processed
ALLOWED_EXTENSIONS=zip
MAX_FILE_SIZE_BYTES=5368709120
MAX_FILES_PER_MOVE=200
DEFAULT_FILES_PER_PAGE=20
PAGE_SIZE_OPTIONS=20,50,100,200
MAX_FILES_PER_PAGE=200
MAX_FILENAME_LENGTH=255

DATABASE_PATH=data/file_mover.db
SQLITE_BUSY_TIMEOUT_MS=10000
BACKUP_DIR=backups
HISTORY_LIMIT=200
EXCEL_EXPORT_LIMIT=5000

REPORT_DIR=reports
REPORT_RETENTION_DAYS=30
BATCH_RETENTION_HOURS=168
MAX_ACTIVE_BATCHES_PER_USER=3

LOG_DIR=logs
ACCESS_LOG=logs/gunicorn-access.log
ERROR_LOG=logs/gunicorn-error.log
LOG_MAX_BYTES=10485760
LOG_BACKUP_COUNT=10
LOG_RETENTION_DAYS=30

LDAP_SERVER=ldaps://ldap.example.com:636
LDAP_USE_SSL=true
LDAP_CA_CERT_FILE=certs/company-root-ca.pem
LDAP_CONNECT_TIMEOUT=10
LDAP_USER_DN_TEMPLATE=
LDAP_BIND_DN=CN=svc_filemover,OU=Service Accounts,DC=example,DC=com
LDAP_BIND_PASSWORD=retrieve-from-secret-manager
LDAP_BASE_DN=DC=example,DC=com
LDAP_USER_FILTER=(sAMAccountName={username})
LDAP_GROUPS_REQUIRED=CN=FileMoverUsers,OU=Groups,DC=example,DC=com;CN=MiddlewareSupport,OU=Groups,DC=example,DC=com
LDAP_GROUP_MATCH_MODE=ANY
LDAP_NESTED_GROUPS_ENABLED=false
LDAP_GROUP_ATTRIBUTE=memberOf
LDAP_EMAIL_ATTRIBUTE=mail
LDAP_DISPLAY_NAME_ATTRIBUTE=cn

SESSION_COOKIE_SECURE=true
SESSION_TIMEOUT_MINUTES=30
LOGIN_MAX_ATTEMPTS=5
LOGIN_WINDOW_SECONDS=300

MAIL_ENABLED=true
SMTP_HOST=smtp.example.com
SMTP_PORT=25
SMTP_TIMEOUT_SECONDS=20
MAIL_FROM_ADDRESS=file-mover@example.com
MAIL_FROM_NAME=File Mover Portal
